"""removed text from transcription

Revision ID: 289fb4de8af4
Revises: 4db131b559eb
Create Date: 2025-02-19 20:26:35.447459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289fb4de8af4'
down_revision = '4db131b559eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
