"""added transcriptions

Revision ID: 4db131b559eb
Revises: 49f98904ceb2
Create Date: 2025-02-19 13:48:51.874740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db131b559eb'
down_revision = '49f98904ceb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('track_id', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ts_add', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('transcription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_segment')
    op.drop_table('transcription')
    # ### end Alembic commands ###
