"""added title to section

Revision ID: 6263cbee262e
Revises: 4f13cc7cb696
Create Date: 2025-01-19 18:21:49.555385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6263cbee262e'
down_revision = '4f13cc7cb696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
